# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_anime_wrappers", use_symbols = TRUE, package_name = "anime")

#' @usage NULL
#' @useDynLib anime, .registration = TRUE
NULL

init_anime <- function(source, target, distance_tolerance, angle_tolerance) .Call(wrap__init_anime, source, target, distance_tolerance, angle_tolerance)

interpolate_extensive_ <- function(source_var, anime) .Call(wrap__interpolate_extensive_, source_var, anime)

interpolate_intensive_ <- function(source_var, anime) .Call(wrap__interpolate_intensive_, source_var, anime)

get_matches_ <- function(anime) .Call(wrap__get_matches_, anime)


# nolint end
