# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_anime_wrappers", use_symbols = TRUE, package_name = "anime")

#' @usage NULL
#' @useDynLib anime, .registration = TRUE
NULL

rnet_match_two_trees <- function(x, y, distance_tolerance, angle_tolerance) .Call(wrap__rnet_match_two_trees, x, y, distance_tolerance, angle_tolerance)

init_anime <- function(x, y, distance_tolerance, angle_tolerance) .Call(wrap__init_anime, x, y, distance_tolerance, angle_tolerance)

interpolate_extensive <- function(var, anime) .Call(wrap__interpolate_extensive, var, anime)


# nolint end
